on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: martolini/wait-for-pypi-action
        with:
          package_name: databutton2
          package_version: 0.6.19
          timeout: 30
          delay: 1